name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Adjust this to the branch you are using

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    # Step 4: Package the Lambda function and its dependencies
    - name: Package Lambda code
      run: |
        mkdir -p lambda_package
        cp split_video.py lambda_package/
        cp -r venv/lib/python3.8/site-packages/* lambda_package/  # Include all dependencies
        cd lambda_package
        zip -r ../lambda.zip .

    # Step 5: Deploy to Lambda
    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code --function-name your-lambda-function-name --zip-file fileb://lambda.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'  # Adjust to your region
